src/icalendar/parser.py
We encountered surprising slowness when working with iCalendar objects that
have large inline attachments (e.g., base64-encoded images). This commit
improves the runtime of `foldline()` from ~7 minutes (!) to 500ms when
invoked on a 1MB string of non-ASCII data, and to 17ms on a 1MB ASCII string.
=> Improve foldline() performance

src/icalendar/prop.py
Without this fix following code does not work:
p = vPeriod((datetime.datetime(2016, 5, 20, 9, 0), datetime.datetime(2016, 5, 20, 10, 0)))
print(p)
=> fix vPeriod.__repr__

CHANGES.rst, docs/credits.rst, src/icalendar/cal.py, src/icalendar/parser.py, src/icalendar/prop.py, src/icalendar/tests/test_fixed_issues.py, src/icalendar/tests/test_unit_cal.py
Date-time was recognized incorrectly as a date or time. This resulted
in wrong representation of some iCalendar strings.
Also adds "errors" list in Component for saving error strings from parsing.
https://github.com/collective/icalendar/issues/174
https://github.com/collective/icalendar/issues/168
=============================================================
This is my first fork and pull request ever, hopefully I did it right.
=> Fixes bug when date-time is recognized as time

CHANGES.rst, src/icalendar/cal.py, src/icalendar/tests/test_fixed_issues.py, src/icalendar/tests/test_unit_cal.py
Hi,
Found an IndexError in Component.from_ical() at https://github.com/collective/icalendar/blob/master/src/icalendar/cal.py#L350 so I replaced it with ValueError instead.
Also added \_\_bool\_\_() in Component so the instances of the class return True on bool() check (https://github.com/collective/icalendar/issues/141). Without it, the check at https://github.com/collective/icalendar/blob/master/src/icalendar/cal.py#L317 might always fail and raise Exception even for Components with ignore_exceptions == True.
=> IndexError fixes + bool(Component) to return True

CHANGES.rst, src/icalendar/cal.py
https://github.com/collective/icalendar/issues/176
======
Should we ever get the strict mode described in https://github.com/collective/icalendar/issues/28, the properties description here needs to be correct. RFC5545 is not so easily readable so some of the properties might still be missing even in this patch. I should hope not, though.
=> Updated components to better conform to RFC 5545

CHANGES.rst, src/icalendar/cal.py, src/icalendar/tests/test_fixed_issues.py
cal.Component.is_broken got removed with 3.9.2 but should not have been
removed before 4.0.0
This should (partly) fix #184
=> Reintroduce cal.Component.is_broken

src/icalendar/prop.py, src/icalendar/tests/test_fixed_issues.py
This is a hotfix to https://github.com/collective/icalendar/issues/184. By the time https://github.com/collective/icalendar/issues/187 is closed vDDDTypes class would probably be removed to achieve the strong property types described in RFC5545.
=> Added PERIOD value type to date types

CHANGES.rst, README.rst, setup.py
setuptools is shipped with Python, no need to include it as a requirement. It
is bad form to include it as a requirement as pip will try to pull in the
latest version.
=> Drop requirement for setuptools package from setup.py

.gitattributes
This causes old PRs to add the changelog entry to already released
versions. It happened to me while rebasing #207
=> Remove custom merge strategy for changelog

CHANGES.rst, setup.cfg, src/icalendar/parser.py, src/icalendar/tests/hypothesis/test_fuzzing.py, tox.ini
This reveals a failure: The character `\u2028` in a value is silently discarded. A quick
look at the iCalendar RFC didn't make it obvious that this character wouldn't
be allowed.
=> Introduce Hypothesis for testing

README.rst
Hopefully will fix this on RTD: https://ptpb.pw/So2f.png
Before (on GitHub): https://ptpb.pw/7sB8.png
After: https://ptpb.pw/yapf.png
=> readme: Remove unnecessary indentation

CHANGES.rst, src/icalendar/cal.py
This deals with #218 so far, as it prints a proper warning when the assert is failing and prevents the creation of badly broken VEVENTS.
=> Assertion for VTIMEZONE sub-components' DTSTART

CHANGES.rst, docs/credits.rst, src/icalendar/cal.py, src/icalendar/tests/test_fixed_issues.py
Following on from #237, I realised this problem only occurs when using python 2. I've done the inexact conversion to str only when running in python 2. This retains the full zone name in python 3 but unfortunately makes timezone handling slightly different when running in different python versions. What do you think?
=> Fix non-ascii TZID and TZNAME handling in python 2

CHANGES.rst, src/icalendar/parser.py, src/icalendar/prop.py, src/icalendar/tests/test_fixed_issues.py, src/icalendar/tests/test_property_params.py, src/icalendar/tests/test_unit_cal.py, src/icalendar/tests/test_unit_prop.py
Invalid escape sequences have been deprecated in Python 3.6. See:
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior
> A backslash-character pair that is not a valid escape sequence now generates a DeprecationWarning. Although this will eventually become a SyntaxError, that will not be for several Python releases.
When warnings are enabled, this appears as:
```
DeprecationWarning: invalid escape sequence ...
```
Sequences discovered through test suite.
=> Fix invalid escape sequences in string and bytes literals

setup.py
Always explicitly close files. Use a context manager to make this easier.
=> Fix ResourceWarnings in setup.py when Python warnings are enabled

.travis.yml, CHANGES.rst, README.rst, bootstrap.py, setup.py, src/icalendar/cal.py, src/icalendar/caselessdict.py, src/icalendar/parser.py, src/icalendar/tests/__init__.py, src/icalendar/tests/hypothesis/test_fuzzing.py, src/icalendar/tests/test_encoding.py, src/icalendar/tests/test_fixed_issues.py, src/icalendar/tests/test_icalendar.py, src/icalendar/tests/test_multiple.py, src/icalendar/tests/test_property_params.py, src/icalendar/tests/test_recurrence.py, src/icalendar/tests/test_time.py, src/icalendar/tests/test_timezoned.py, src/icalendar/tests/test_unit_cal.py, src/icalendar/tests/test_unit_caselessdict.py, src/icalendar/tests/test_unit_parser_tools.py, src/icalendar/tests/test_unit_prop.py, src/icalendar/tests/test_unit_tools.py, tox.ini
I would humbly like to suggest icalendar drop support for Python 2.6.
The last release of Python 2.6 was 2013-10-29, almost 4 years ago. It is no longer receiving security or bug fixes.
https://www.python.org/dev/peps/pep-0361/
The pip project itself has recently dropped support for 2.6. At the beginning of the year, their numbers estimated that Python 2.6 accounts for ~2% of their downloads.
pypa/pip#4343
For projects that still use Python 2.6, they can continue to pip install an older version.
I've tried my best to remove as much 2.6 specific code as I can, including the `'Programming Language :: Python :: 2.6'` trove classifier from setup.py. I've also removed Travis CI testing, which should result
in slightly faster testing and fewer wasted resources.
Changed:
* Update trove …
=> Drop support for Python 2.6

.travis.yml
Can slightly improve build times and reduce load on PyPI servers.
For documentation on cache support, see:
https://docs.travis-ci.com/user/caching/#pip-cache
=> Add pip cache support to Travis CI configuration

.travis.yml
Per the feedback from @polyzen in PR #246, in YAML, numeric bare strings are interpreted as floats, not strings. Versions are strings and should not be coerced to a float. For example, 7.10 isn't the same as 7.1.
For more details, see Travis issue:
https://github.com/travis-ci/docs-travis-ci-com/pull/1537
=> Quote all version strings in Travis CI configuration

CHANGES.rst, docs/credits.rst, src/icalendar/tests/hypothesis/test_fuzzing.py
The fuzzing configuration introduced by https://github.com/collective/icalendar/pull/191 *did* find a novel issue in its first run. However, it is unable to run on travis-ci due to taking too long without output. I tried running it locally to make sure it wasn't Travis being Travis, and sure enough, on my i9-9880H, the operation took well over 20 minutes before I stopped it.
Because of this, I've reduced the number of examples that Hypothesis will run. This will catch fewer errors but help us get PRs back on track.
Ping @untitaker, who introduced this change originally
=> Calm down fuzzing

.readthedocs.yml, CHANGES.rst
Add a [Read the Docs configuration file](https://docs.readthedocs.io/en/stable/config-file/v2.html). This config file has a few advantages:
* Versioning your Read the Docs build options (eg. the requirements file, Python version) rather than having those live only in the RTD dashboard.
* There are some things that can only be configured in the config file although icalendar doesn't rely on them currently.
The [current build](https://readthedocs.org/projects/icalendar/builds/9067589/) on Read the Docs is failing. There are a few issues but I verified that this config file would solve them:
* The docs requirements file isn't installed and so `icalendar` itself isn't installed. The docs build relies on this package being installed.
* The requirements file specifies installing `.` which only …
=> Add a readthedocs config file

CHANGES.rst, docs/credits.rst, src/icalendar/prop.py, src/icalendar/tests/test_unit_prop.py
Use default type `vText` when converting recurrence definition to ical string. 
This is similar to `from_ical` behavior, that allows to set anything as recurrence key and treats it as `vText`; but at the same time, `to_ical` has strictly limited list of supported types and no default type, so the rule `x == vDataType.from_ical(VDataType(x).to_ical())` (from https://github.com/collective/icalendar/blob/master/src/icalendar/prop.py#L33) is broken. 
Furthermore, with this we can use non-standard recurrence keys (like `BYEASTER` supported by `deteutil`). 
This is a fix without breaking changes.
=> Default type vText when converting vRecur to ical

CHANGES.rst
Because of release along the way, the PR #299 provided an incorrect entry to CHANGELOG. This PR fix it.
=> Fix incorrect CHANGELOG entry

CHANGES.rst, src/icalendar/cal.py, src/icalendar/tests/test_timezoned.py
Fix for https://github.com/collective/icalendar/issues/303
This also reactivates the testcase that used to fail.
=> Correct the handling of rrules within timezone definitions.

src/icalendar/prop.py
I was browsing the code related to an issue I had with [khal](https://github.com/pimutils/khal). I'm not sure why it doesn't break anything, but this was probably a typo.
=> fix variable typo

CHANGES.rst, CONTRIBUTING.rst, docs/credits.rst, docs/install.rst, tox.ini
This pull request aims at clarifying how to setup icalendar for development.
=> Document Setup process for development

README.rst
It adds two badges.
shows which version is there - quite useful to know and nice to see that it changes after deploy
makes sure we know that this is important and used a lot!
=> add badges for download and PyPI version

README.rst
https://shields.io provides more distinct badges for the status.
Also, the links got replaced to that they point to the filtered actions.
This provides more clarity about the tests for people visiting PyPI and the documentation.
=> replace GitHub actions badges

README.rst
@mauritsvanrees @geier
I created this PR to make the purpose of the branches clear.
There is some difference between the branch purpose as pointed out in https://github.com/collective/icalendar/discussions/360:
> Increase master branch version to 5 (or 6 if needed). This should keep working on Plone 6.0 (which is near beta), which means Python 3.7-3.10.
and this PR https://github.com/collective/icalendar/pull/366
> [Require Python 3.8.](https://github.com/collective/icalendar/pull/366/commits/c73cab2c101beaf2a13c7e8d7037da3340123033)
How to approach this?
=> describe purpose of the branches master and 4.x

docs/conf.py, setup.py, src/icalendar/__init__.py, src/icalendar/cal.py, src/icalendar/caselessdict.py, src/icalendar/cli.py, src/icalendar/compat.py, src/icalendar/parser.py, src/icalendar/parser_tools.py, src/icalendar/prop.py, src/icalendar/tests/test_encoding.py, src/icalendar/tests/test_fixed_issues.py, src/icalendar/tests/test_icalendar.py, src/icalendar/tests/test_multiple.py, src/icalendar/tests/test_property_params.py, src/icalendar/tests/test_recurrence.py, src/icalendar/tests/test_time.py, src/icalendar/tests/test_timezoned.py, src/icalendar/tests/test_unit_cal.py, src/icalendar/tests/test_unit_caselessdict.py, src/icalendar/tests/test_unit_parser_tools.py, src/icalendar/tests/test_unit_prop.py, src/icalendar/tests/test_unit_tools.py, src/icalendar/timezone_cache.py, src/icalendar/tools.py
`> find . -iname "*.py" -exec pyupgrade --py38-plus {} \;`
=> Remove any syntax required for python < 3.8

CHANGES.rst, src/icalendar/prop.py
This is a patch to prevent the UTC tzid to be shown when passing datestamps with tzid=utc, and utc is not pytz.utc
Test code is missing as for now.  (I'm curious if the test code passes, as it didn't pass for #334).
=> UTC tzid fix

.gitignore, venv/pyvenv.cfg
This deletes and ignores a folder people use for testing.
see https://github.com/collective/icalendar/pull/324/files#diff-1da1691e79f01938d280502610d5e64a64ca71ef6efaa9fa5addbc4a8082843b
=> ignore venv folder

src/icalendar/tests/test_icalendar.py
This is the same as #330 with tests running.
=> Tirkarthi fix assert - #330

src/icalendar/tests/test_icalendar.py
The deprecated aliases were removed in Python 3.11 in python/cpython#28268 . Fixes https://github.com/collective/icalendar/issues/344
=> Refactor deprecated unittest aliases for Python 3.11 compatibility.

CHANGES.rst
While 4.1.0 contains the same changes as 5.0.0a1, it is confusing to
have a release out which is not mentioned in the changelog at all.
fix #393
=> add CHANGELOG entry for 4.1.0

requirements_docs.txt
This is a temporary fix for #419, version pinning the Sphinx version to make master green again.
=> fix Sphinx build

requirements_docs.txt
This reverts commit f4b50d6b9621f71f5fb1c128dd010789093603e8.
This is to check if the usual, non-pinned installation works like it did before.
fixes #419
=> Revert "fix Sphinx build"

src/icalendar/tests/test_parsing.py
Using getattr can be avoided by using getitem
=> remove getattr() call where [] can be used

README.rst
This refers to https://github.com/collective/icalendar/issues/325
The idea: We want to know when the readTheDocs build fails.
=> add badge for https://readthedocs.org/projects/icalendar/

.github/workflows/tests.yml
- verifies tag name and version
- deploy tags only
- uses environments to access deploy secrets
- deploys after all tests have succeeded
contributes to https://github.com/collective/icalendar/issues/446
=> add deployment on tags

docs/maintenance.rst
The new section for releases comes up here:
https://pypi.org/project/icalendar/5.0.0/#changelog This should not be visible on PyPI.
This fixes the release process.
=> move new section in the changelog

CHANGES.rst, docs/credits.rst, setup.cfg, setup.py
Fixes two setuptools deprecation warnings:
1. "The license_file parameter is deprecated, use license_files instead."
2. "Installing 'icalendar.tests.calendars' as data is deprecated, please list it in `packages`." and alike
The second one I've fixed the "easier" way by using `find_namespace_packages()`. If you prefer, I can change that to adding `__init__.py` files to all icalendar/tests subdirectories.
=> fix setuptools deprecation warnings

setup.cfg
Very minor thing: I see that release [5.0.0 has a universal wheel](https://pypi.org/project/icalendar/5.0.0/#files), but the package is Python 3 only.
And `zest.releaser.create-wheel` is not needed, since we already have a `bdist_wheel` section.
=> Do not create a universal wheel for the release.

src/icalendar/tests/calendars/pr_480_summary_with_colon.ics, src/icalendar/tests/test_components_break_on_bad_ics.py
Some message parts may be hidden from the assertion because of multiple splitting. See #473 and [this](https://github.com/collective/icalendar/pull/473/files)for context.
=> Adjust assertion of max_error_length test

CHANGES.rst, src/icalendar/prop.py, src/icalendar/tests/test_unit_prop.py
This adds tests and an implementation of `__hash__` for vDDDTypes to fix #487.
- add `__hash__`
- add `.dt` comparison to `__eq__` so that the equality is really tested.
=> implement hash and __eq__ for vDDDTypes

docs/maintenance.rst
The links to teams are only available to members of the team for everyone else it returns a 404 error
Discussion here:
https://github.com/collective/icalendar/commit/a8bbfb9349cfc2baa5ef1c2ec02514accb0833d1#commitcomment-91538993
=> remove dead link

docs/usage.rst
The example uses the pytz module:
`event.add('dtstart', datetime(2005,4,4,8,0,0,tzinfo=pytz.utc))`
But doesn't import it
=> add missing import pytz in example

docs/usage.rst
I suggest it might be a nice idea to display the content of the file generated in the example
=> display file content of example

README.rst
The labels were broken. The URL has changed.
See also https://github.com/badges/shields/issues/8671
=> correct status badges for branches master and 4.x

CHANGES.rst, docs/credits.rst, src/icalendar/prop.py, src/icalendar/tests/test_unit_prop.py
Add support for BYWEEKDAY in the RRULE based on https://github.com/collective/icalendar/issues/268
Background: [dateutil](https://dateutil.readthedocs.io/en/stable/rrule.html) renamed BYDAY to BYWEEKDAY to "avoid the ambiguity of that keyword". Note that RFC 5545 uses BYDAY only.
From https://github.com/collective/icalendar/issues/268
=> Issue 268 - support for BYWEEKDAY

CHANGES.rst, docs/credits.rst, src/icalendar/prop.py
refactored DURATION_REGEX and vDuration.from_ical func
=> refactored DURATION_REGEX

CHANGES.rst, docs/credits.rst, src/icalendar/prop.py, src/icalendar/tests/test_recurrence.py
Issue 518: https://github.com/collective/icalendar/issues/518
Updated WEEKDAY_RULE regex as proposed in my issue report.
Added tests to test_recurrence.py giving basic coverage for to_ical() with BYDAY values. All tests pass (run with pytest). Without the fix, the new tests give 3 failures.
Added fix to CHANGES.rst & added myself to credits.rst.
=> Fix for issue 518 (to_ical() with RRULE BYDAY values>=10)

.github/workflows/tests.yml, CHANGES.rst, tox.ini
Also, run the Python 3.11 tests with the latest Python 3.11, instead of a release candidate.
In the last two weekly cron tests, the plone tests fail with:
ModuleNotFoundError: No module named 'plone.app.event'
I see the same locally, and I have no idea why.
This seems a good time to stop running the `plone.app.event` tests within `icalendar`.  We ran them until now to prevent changes from creeping in that negatively affect Plone, which is where this module was born.  But so far, nothing like that has happened.  And occasionally these tests break because of reasons that have nothing to do with `icalendar`, so they distract from maintenance of this package.  So let's stop doing this.
=> No longer run the plone.app.event tests.

.github/workflows/tests.yml, CHANGES.rst
This is now possible:
https://github.com/actions/setup-python#caching-packages-dependencies
=> Move pip cache into Python setup

.readthedocs.yml, CHANGES.rst
see https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
> The configuration key build.os is required to build your documentation.
#538
=> Update read the docs

CHANGES.rst, docs/credits.rst, src/icalendar/prop.py, src/icalendar/tests/test_recurrence.py
Issue 518 fix for the 4.x branch (already fixed in master branch). Issue: https://github.com/collective/icalendar/issues/518
The fix itself is the same as in the master branch. The test code has been adapted because the corresponding test code in 4.x uses the unittest module, rather than pytest as in the master branch.
All tests pass (run with setup.py test). Without the fix, the new tests give 3 failures.
Justification for inclusion in 4.x branch: It's a crashing bug. The fix is low risk (never say zero risk!).
=> 4.x branch: Fix for issue 518 (to_ical() with RRULE BYDAY values>=10)

CHANGES.rst, docs/about.rst
Updating about.rst for #527 
Added to changes.rst
I do not wish to be included on the docs/credits/rst
=> Update About document

CHANGES.rst, docs/credits.rst, src/icalendar/prop.py
Exposed by running in `python3 -b` mode.
=> Fix `vText.__repr__` `BytesWarning`

CHANGES.rst, docs/credits.rst, src/icalendar/cal.py, src/icalendar/tests/test_issue_557_encode_native_parameters.py
Fixes #557
- converts Component._encode to staticmethod
- makes testing easier
- keeps compatibility to existing code
- introduces test cases for expected behavior
- changes Component._encode accordingly
=> Component._encode: merge instead of ignore parameters on natives

CHANGES.rst, src/icalendar/cli.py, src/icalendar/tests/test_cli_tool.py
This makes up for a much nicer UX for users of the cli utility.
Before this patch the start and end datetimes were always displayed with a fixed timezone (the timezone of the calendar creator).
This meant that users had to manually calculate the time in their own timezone.
With this patch the times are printed in the expected format, i.e. in the user's own local timezone.
It seems that in 7a8d584b an attempt was already made to implement this, but unfortunately `start.astimezone(start.tzinfo)` is a no-op and does absolutely nothing. Instead no arguments have to be passed to the `astimezone()` function to convert to the user's timezone, see https://docs.python.org/3/library/datetime.html#datetime.datetime.astimezone
The unit test has been adapted to check for the output in the correct …
=> cli: Display datetimes in local timezone

CHANGES.rst, src/icalendar/prop.py
Needed as 088eea7 adds comparison of elements this makes sure that they
are compared by value instead of by reference.
This party fixes https://github.com/niccokunzmann/x-wr-timezone/issues/8. I
think the unit tests should be moved here as well.
=> Add some __eq__

.github/workflows/tests.yml, CHANGES.rst
fix #563
@niccokunzmann will this work? I've never used GitHub actions before
=> add deploy-github-release workflow

CHANGES.rst, src/icalendar/fuzzing/build.sh
I'm currently working on switching the OSS Fuzz build to use the fuzzing harnesses hosted in icalendar. In doing that, I noticed that this change required updating the find path in the build.sh script. I tested it locally and the fuzz harnesses are able to build.
=> Fix Oss Fuzz Build Error

CHANGES.rst, src/icalendar/fuzzing/ical_fuzzer.py, src/icalendar/parser_tools.py, src/icalendar/prop.py, src/icalendar/tests/test_oss_fuzz_errors.py
This PR introduces the fixes to address two bugs discovered by OSS Fuzz and adds two test cases to ensure that they are not reintroduced down the line.
The bugs are as follows:
1) Type mismatch in vDDDlists.to_ical when given a date-time that resolves to a string and is joined as bytes
2) Attempting to pop from an empty stack when parsing 'BEGIN' and 'END' in to_ical
=> Add fixes for OSS-Fuzz bugs and test cases

CHANGES.rst, src/icalendar/cal.py, src/icalendar/fuzzing/ical_fuzzer.py, src/icalendar/parser_tools.py, src/icalendar/prop.py, src/icalendar/tests/test_oss_fuzz_errors.py
This PR updates the fuzzer harness for OSS-Fuzz
=> Updated fuzzer harness

CHANGES.rst, src/icalendar/fuzzing/ical_fuzzer.py
This PR adds more substrings to the fuzzer's exception checks to ensure that it does not report expected exceptions as crashes. With this merged, deeper coverage should be achieved to discover more edge cases.
=> Fuzzer Work: Added More Exception Handling

CHANGES.rst, src/icalendar/fuzzing/ical_fuzzer.py
Another quick PR, I added another defined exception that was holding up fuzzer progress and made a tweak to see if we can get more intelligent instrumentation and coverage exploration. 
A suggestion would be collecting all raised exceptions under a common base-class, such as CalendarException, so the fuzzer can just do except CalendarException as opposed to string-matching multiple ValueErrors. This would also help users of the library in their error-handling, as well.
=> Added more instrumentation + caught one more exception

CHANGES.rst, docs/maintenance.rst
I would like to make the roles clearer. GitHub has the collaborator label for those with write access.
=> rename contributor to collaborator

CHANGES.rst, tox.ini
By analysing the code coverage in the test files, we can make sure that we do not accidentially remove a test and that all test code actually is used.
Issues to open:
=> Analyse code coverage in tests

.github/workflows/tests.yml, CHANGES.rst
This fixes #563.
See the [v5.0.12 tag](https://github.com/collective/icalendar/releases/tag/v5.0.12).
=> [WIP] Create GitHub Releases

CHANGES.rst, src/icalendar/tests/test_unit_prop.py
This PR resolve https://github.com/collective/icalendar/issues/605
When adding test case, i still can't figured it out how to trigger __repr__ function. Could you help me with guidance to trigger that?
=> add test case for unit prop

CHANGES.rst, tox.ini
`setuptools` might not be installed. This installs it to build the documentation with Python 3.12.
See also:
- https://stackoverflow.com/a/10538412/1320237
```
phinx v7.3.7 in Verwendung
Configuration error:
There is a programmable error in your configuration file:
Traceback (most recent call last):
File "/home/nicco/icalendar/.tox/docs/lib/python3.12/site-packages/sphinx/config.py", line 509, in eval_config_file
exec(code, namespace)  # NoQA: S102
^^^^^^^^^^^^^^^^^^^^^
File "/home/nicco/icalendar/docs/conf.py", line 2, in <module>
import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
I hope that works with lower versions of Python, too.
=> Make documentation build under Python 3.12

CHANGES.rst, src/icalendar/tests/test_with_doctest.py
When you build a distribution, after this, the tests fail. This guides around this issue.
=> Guide to delete the build folder before testing

CHANGES.rst, README.rst, docs/api.rst, docs/conf.py, docs/credits.rst, src/icalendar/prop.py
Fixes #631.
Depends on #636 for change log consistency.
I also fixed a docstring that returned this error:
```pycon
/Users/stevepiercy/projects/icalendar/src/icalendar/prop.py:docstring of icalendar.prop:4: CRITICAL: Missing matching underline for section title overline.
###########################################################################
```
Sphinx treated that line as a page title, and a blank line resolved the issue.
I'm not sure whether you want that line to be a comment or displayed, though.
=> Enhance documentation of API

CHANGES.rst
Let's skip the change log entry for this housekeeping chore.
=> Move change log item under correct heading.

CHANGES.rst, src/icalendar/__init__.py, src/icalendar/prop.py
This fixes #67.
See also #630 .
=> Remove unused and untested code

CHANGES.rst, src/icalendar/cal.py, src/icalendar/tests/test_components_break_on_bad_ics.py
Fix #424
Contribute to #630.
`.errors` would be enough.
=> Remove is_broken property

CHANGES.rst, README.rst, docs/maintenance.rst, docs/usage.rst
We switched to `main`, see #627.
=> Rename master to main in docs

CHANGES.rst, README.rst
This compacts the documentation.
Mentions of old versions are removed.
A concise path from 5.x to 6.0 is outlined.
master -> main
Contributes to https://github.com/collective/icalendar/issues/513
=> Update documentation for versions 3.8+

.github/workflows/tests.yml, setup.py, src/icalendar/cal.py, src/icalendar/prop.py, src/icalendar/tests/conftest.py, src/icalendar/tests/prop/test_unit.py, src/icalendar/tests/test_cli_tool.py, src/icalendar/tests/test_components_break_on_bad_ics.py, src/icalendar/tests/test_icalendar.py, src/icalendar/tests/test_issue_116.py, src/icalendar/tests/test_issue_165_missing_event.py, src/icalendar/tests/test_issue_168_parsing_invalid_calendars_no_warning.py, src/icalendar/tests/test_issue_27_period.py, src/icalendar/tests/test_issue_350.py, src/icalendar/tests/test_issue_500_vboolean_for_parameter.py, src/icalendar/tests/test_multiple.py, src/icalendar/tests/test_property_params.py, src/icalendar/tests/test_timezoned.py, src/icalendar/tests/test_unit_cal.py, src/icalendar/tests/test_with_doctest.py
According to https://endoflife.date/python python 3.7 has been EOSed 27 Jun 2023.
Filter all code over `pyupgracde --py38-plus`.
=> drop python<=3.7 support

.github/workflows/tests.yml, CHANGES.rst
use documented way to do coverage in parallel
Context:
- https://github.com/collective/icalendar/actions/runs/9626921659/job/26553447797#step:6:98
- https://github.com/collective/icalendar/pull/633#issuecomment-2184110223
=> Improve coverage report

CHANGES.rst, docs/credits.rst, src/icalendar/__init__.py
This commit improves the namespace management within the `icalendar` directory by adding __all__ attributes to the `__init__.py` files of each module. This allows for clearer control over what is imported when using wildcard imports.
Closes #638
=> Add __all__ attributes to icalendar modules

.github/workflows/tests.yml, CHANGES.rst
Sometimes, we get this error:
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
This PR allows the error to happen while also maintaining the test result and making sure that we actually installed all dependencies.
This is a follow up from
https://github.com/collective/icalendar/pull/644
main branch failed:
https://github.com/collective/icalendar/actions/runs/9663149658/job/26654629821
=> Make coverage report optional in case it fails to submit

CHANGES.rst, docs/usage.rst
=> docs: replace pytz usage to zoneinfo in documentation

CHANGES.rst, docs/Makefile, requirements_docs.txt
Closes #673.
Depends on #664 to get CI to run.
=> Add `sphinx-autobuild` for `livehtml` Makefile target

.github/workflows/tests.yml, CHANGES.rst
This adds a message to the release.
I use this at the OpenWebCalendar.
See this release:
https://github.com/collective/icalendar/releases/tag/v5.0.13
See this release:
https://github.com/niccokunzmann/open-web-calendar/releases/tag/v1.35
=> Create a release message pointing people to the changelog and PyPI

.github/workflows/tests.yml, .readthedocs.yml, CHANGES.rst, tox.ini
This is another try, using coveralls' github action.
Contributes to #677.
=> use coveralls' github action

CHANGES.rst, docs/install.rst
- Use shell instead of bash as a universal shell.
- Use pycon for Python console commands.
- Remove command prompts from shell commands to make them easier to copy and have neutral shell.
- Remove `http.server` option as it's been replaced by `make livehtml`.
Closes #673
=> Add docs for live HTML preview of documentation and clean up.

.github/workflows/ruff.yml, CHANGES.rst
This contributes to #672 
- add github action to test code
=> Ruff formatting

.github/workflows/tests.yml, CHANGES.rst, README.rst, setup.py
The release tag failed for v6.0.0a0.
```
Checking dist/icalendar-6.0.0a0-py3-none-any.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be        
rendered on PyPI.                                                      
line 212: Severe: Title level inconsistent:                            
Changelog                                                              
=========                                                              
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
Checking dist/icalendar-6.0.0a0.tar.gz: FAILED
ERROR    `long_description` has syntax errors in markup and would not be        
rendered on PyPI.                                                      
line 212: Severe: Title level inconsistent: …
```
=> Check distribution build

CHANGES.rst, docs/credits.rst, docs/install.rst
Issue: https://github.com/collective/icalendar/issues/614
----
📚 Documentation preview 📚: https://icalendar--688.org.readthedocs.build/
=> Fix broken link in doc.

CHANGES.rst, src/icalendar/parser.py, src/icalendar/tests/test_parsing.py
This pull request fixes issue #525, where there was a bad replace in parser.py
----
📚 Documentation preview 📚: https://icalendar--694.org.readthedocs.build/
=> Fixed a bad replace in parser.py.

CHANGES.rst, src/icalendar/tests/test_with_doctest.py
On Windows, test_with_doctest.py fails because file and module paths have backslashes on them instead of forward slashes or dots. This PR fixes that by using a forward slash instead of `os.path.join` and by also substituting backslashes by forward slashes to figure out module names.
Happy to address any feedback or to close if it's not a necessary change.
=> Fix test_with_doctest.py to run on Windows.

CHANGES.rst, src/icalendar/prop.py, src/icalendar/tests/prop/test_unit.py, src/icalendar/tests/prop/test_vBinary.py, src/icalendar/tests/prop/test_vCalAddress.py
This PR fixes issue #629 by Improving test coverage in 5 places for production code
----
📚 Documentation preview 📚: https://icalendar--696.org.readthedocs.build/
=> Improved test coverage in 5 places for production code

CHANGES.rst, tox.ini
Having branch coverage information helps when trying to address issues like #698 and #629 (where we used it to find places to test).
This PR adds the `--branch` option to `coverage run` in tox.ini commands.
Possible downsides: test run time will likely increase, coverage numbers will probably go down. Still, the difference should not be huge and it will help improving coverage in the long term.
=> Enable collection of branch coverage on test runs

CHANGES.rst, docs/install.rst, docs/maintenance.rst, pyproject.toml, src/icalendar/__init__.py, src/icalendar/tests/test_with_doctest.py, src/icalendar/version.py
Following: https://icalendar.readthedocs.io/en/latest/maintenance.html#new-releases
- update release process
- ruff format some files
- use version variable from icalendar.version
- update aplha to stable
----
📚 Documentation preview 📚: https://icalendar--710.org.readthedocs.build/
=> Release v6.0.0

CHANGES.rst, pyproject.toml, src/icalendar/__init__.py, src/icalendar/cal.py, src/icalendar/prop.py, src/icalendar/tests/test_issue_662_component_properties.py, src/icalendar/tests/test_with_doctest.py
This is a contribution to #662. 
Calculation of event start and end are actually quite complex.
This also contributes to #716 because the calculation of start and end are way easier then.
----
📚 Documentation preview 📚: https://icalendar--721.org.readthedocs.build/
=> Start calculating event start and end

CHANGES.rst, pyproject.toml, src/icalendar/tests/test_create_release.sh
fixes #712
> To Reproduce -> These commands work now. The docs are added.
----
📚 Documentation preview 📚: https://icalendar--720.org.readthedocs.build/
=> Add docs folder

.github/workflows/tests.yml, CHANGES.rst, README.rst, pyproject.toml, tox.ini
Closes #723 
- add python 3.13 support
- all tests passed with new python version - no need to update files
----
📚 Documentation preview 📚: https://icalendar--728.org.readthedocs.build/
=> test python 3.13 support

CHANGES.rst, docs/api.rst
icalendar.timezone was absent from the API docs.
=> Complete API documentation

CHANGES.rst, src/icalendar/cal.py
This cherry-picks the commits by @Firdous2307.
```
git fetch https://github.com/Firdous2307/icalendar.git add-rfc-documentation
git checkout -b rfc-docs
git cherry-pick a27b146
git push
```
@stevepiercy, your suggested edits are included.
----
📚 Documentation preview 📚: https://icalendar--738.org.readthedocs.build/
=> Follow up #730 - rfc 5545 docs on components

CHANGES.rst, docs/usage.rst
From https://github.com/collective/icalendar/issues/626
I didn't change much of the content for now.
----
📚 Documentation preview 📚: https://icalendar--739.org.readthedocs.build/
=> merge file structure with overview section

CHANGES.rst, docs/credits.rst, src/icalendar/prop.py
Added ``__doc__`` string documentation for ``vDate``, ``vBoolean``, ``vCalAddress``, ``vDuration``, ``vFloat``, ``vGeo``, ``vInt``, ``vPeriod``, ``vText``, ``vTime``, ``vUTCOffset`` and ``vUri``.
Added ``vTime``  description, but examples from icalendar are not implemented because timezone support is not implemented.
----
📚 Documentation preview 📚: https://icalendar--745.org.readthedocs.build/
=> issue-742  

CHANGES.rst, docs/credits.rst, src/icalendar/prop.py, src/icalendar/tests/prop/test_vWeekday.py
This pr adds the `sign` and `weekday` properties to `vWeekday` components, so that users of this library don't have to manually parse these. 
I decided to just make the existing variables available, but I could also combine `sign` and `relative` into one variable, if that is wanted.
Fixes: #749 
----
📚 Documentation preview 📚: https://icalendar--750.org.readthedocs.build/
=> Add `sign` and `weekday` attributes to `vWeekday` components

CHANGES.rst, src/icalendar/tests/test_with_doctest.py
When the documentation tests fail, this change will print the result of that.
Before, there was no hint, now you can see this for example:
```
**********************************************************************
File "/home/nicco/icalendar/src/icalendar/tests/../../../docs/usage.rst", line 408, in usage.rst
Failed example:
f.write(cal.to_ical())
Expected:
733
Got:
775
**********************************************************************
File "/home/nicco/icalendar/src/icalendar/tests/../../../docs/usage.rst", line 416, in usage.rst
Failed example:
print(cal.to_ical().decode('utf-8')) # doctest: +NORMALIZE_WHITESPACE
Expected:
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//My calendar product//mxm.dk//
BEGIN:VEVENT
SUMMARY:Python meeting about calendaring
DTSTART:20050404T080000Z …
```
=> Print result of doctest failure

CHANGES.rst, src/icalendar/cal.py, src/icalendar/parser_tools.py, src/icalendar/tests/fuzzed/__init__.py, src/icalendar/tests/prop/test_windows_to_olson_mapping.py, src/icalendar/tests/test_issue_722_generate_vtimezone.py, src/icalendar/timezone/equivalent_timezone_ids.py
These changes aim to fix bugs in the code and in the tests. 
However, I didn't catch the original intentions behind some parts of the code. So please double check.
----
📚 Documentation preview 📚: https://icalendar--766.org.readthedocs.build/
=> Probably bugs

README.rst
We do not have a mailing list any more.
This updates the links.
----
📚 Documentation preview 📚: https://icalendar--761.org.readthedocs.build/
=> Link to issue tracker and discussions

CHANGES.rst, docs/conf.py
This adds intersphinx mapping of Python objects and our dependencies.
Before:
Now, bool and date are a link:
----
📚 Documentation preview 📚: https://icalendar--770.org.readthedocs.build/
=> Add intersphinx

docs/security.rst
This contributes to #771.
This adds the link to our security advisory board (empty).
----
📚 Documentation preview 📚: https://icalendar--772.org.readthedocs.build/
=> Add link to security advisory  board

CHANGES.rst, README.rst
The first example is very useful. It should be as concise as possible.
This is tested by the tests.
----
📚 Documentation preview 📚: https://icalendar--767.org.readthedocs.build/
=> Shorten first example

CHANGES.rst, src/icalendar/prop.py, src/icalendar/tests/prop/test_vCalAddress.py
This adds a few convenience attributes.
- name
- email
- params (type)
----
📚 Documentation preview 📚: https://icalendar--783.org.readthedocs.build/
=> Add name and email attribute to vCalAddress

CHANGES.rst, docs/credits.rst, src/icalendar/prop.py, src/icalendar/tests/prop/test_constructors.py
Added `params={}` to class constructors in `icalendar.prop`.
Initialized `params` member in classes with `params` argument.
----
📚 Documentation preview 📚: https://icalendar--785.org.readthedocs.build/
=> added params argument to class constructors

CHANGES.rst
new release, see https://icalendar.readthedocs.io/en/latest/maintenance.html
----
📚 Documentation preview 📚: https://icalendar--786.org.readthedocs.build/
=> version 6.1.2

CHANGES.rst, src/icalendar/timezone/tzid.py
I accidentally worked on the `main` branch. Here is the pull request.
- use existing lookup table only to identify equivalent timezones
- return a tuple of possible timezone ids
- first in this tuple is the timezoneid passed
- test dateutil, pytz, zoneinfo
- add support for dateutil.tz.tzutc
This fixes #780
=> Reapply "Create stability around timezone identification"

CHANGES.rst, pyproject.toml
Hatchling `1.27.0` added support for [PEP 639](https://peps.python.org/pep-0639/) license expressions. Update the project metadata for it.
=> Use license expression for project metadata

CHANGES.rst, src/icalendar/attr.py, src/icalendar/cal.py, src/icalendar/tests/test_rfc_7986.py
This is a start on #655 and adds these attributes the the calendar component:
- NAME with compatibility to X-WR-CALNAME
- DESCRIPTION with compatibility to X-WR-CALDESC
- COLOR with compatibility to X-APPLE-CALENDAR-COLOR
----
📚 Documentation preview 📚: https://icalendar--801.org.readthedocs.build/
=> Add VCALENDAR properties NAME, DESCRIPTION and COLOR as attributes

CHANGES.rst
We use semantic versioning on the project. This is now also written into the changelog.
----
📚 Documentation preview 📚: https://icalendar--827.org.readthedocs.build/
=> Document semver

CHANGES.rst, src/icalendar/attr.py, src/icalendar/cal.py, src/icalendar/tests/conftest.py, src/icalendar/tests/test_issue_720_uid_property.py
This adds unified access to UID.
Fix #740 
----
📚 Documentation preview 📚: https://icalendar--835.org.readthedocs.build/
=> Add UID property

.readthedocs.yml, CHANGES.rst
By building the package and pulling the tags, we should be able to build the documentation so it shows the version of the package.
@stevepiercy What are your thoughts on the commands? Would it be better to put them into make?
Contributes to #826
=> get tags and set version

docs/maintenance.rst
This makes it nicer to release a new version.
----
📚 Documentation preview 📚: https://icalendar--840.org.readthedocs.build/
=> Introduce tag variable

.coveragerc, .gitignore, CHANGES.rst
This excludes the type checking block from the test coverage report.
This is not covered any way because it is never run.
Before:
```
Name                                                                                             Stmts   Miss Branch BrPart  Cover
src/icalendar/alarms.py                                                                            129      4     44      3    96%
```
after:
```
Name                                                                                             Stmts   Miss Branch BrPart  Cover
src/icalendar/alarms.py                                                                            126      2     42      2    98%
```
----
📚 Documentation preview 📚: https://icalendar--858.org.readthedocs.build/
=> Exclude type checking block from test coverage

README.rst
This creates a link in related projects to another project that does roughly the same.
----
📚 Documentation preview 📚: https://icalendar--862.org.readthedocs.build/
=> link to vobject

CHANGES.rst, src/icalendar/cal/availability.py, src/icalendar/cal/available.py, src/icalendar/tests/test_examples.py, src/icalendar/tests/test_issue_864_examples.py
This fixes #864.
----
📚 Documentation preview 📚: https://icalendar--875.org.readthedocs.build/
=> Add example() to Available and Availability

CHANGES.rst, docs/credits.rst, src/icalendar/cal/calendar.py, src/icalendar/tests/test_issue_844_timezone_placement.py
Fixes #844 by modifying Calendar.add_missing_timezones() to insert VTIMEZONE components at the beginning of the calendar instead of appending them to the end.
The add_missing_timezones() method was placing VTIMEZONE components after VEVENT and other components that reference them. This violates standard iCalendar practices where VTIMEZONE components should appear before components that reference them.
- Modified the insertion logic to place new VTIMEZONE components after any existing VTIMEZONE components but before other component types
- Preserves existing timezone components in their current positions
- Maintains backward compatibility with all existing functionality
- Modified: src/icalendar/cal/calendar.py - Updated add_missing_timezones() method
- Added: …
=> Fix timezone placement in add_missing_timezones()

CHANGES.rst, src/icalendar/cal/calendar.py, src/icalendar/cal/event.py, src/icalendar/tests/test_issue_857_enhanced_api.py
Fixes #857 by implementing the remaining API usability enhancements requested in the issue.
Issue #857 identified several pain points with the current iCalendar API:
- Users must know specific RFC field names (PRODID, VERSION, DTSTART, etc.)
- Manual calculation of end times from start + duration
- No validation to ensure calendars are complete before output
- Complex workflow requiring extensive RFC knowledge
Building on the foundation from merged PR #845, this implements the remaining enhancements:
```python
cal = Calendar()
cal.add('prodid', '-//My Org//My App//EN')
cal = Calendar.new(organization="example.org", name="My App", language="en")
```
```python
event = Event.new(start=datetime(2026, 3, 19, 12, 30))
event.end = datetime(2026, 3, 19, 14, 30)  # User calculates
event = …
```
=> Implement enhanced API usability improvements for issue #857

CHANGES.rst, src/icalendar/prop.py, src/icalendar/tests/test_issue_870_vcaladdress_new.py
This PR implements the  method for the  class to provide a consistent API with other icalendar components like .
✅ **vCalAddress.new() method implementation:**
- Email as first positional parameter
- Automatic mailto: prefix handling (adds if missing)
- All RFC 5545 parameters supported: CN, CUTYPE, DELEGATED-FROM, DELEGATED-TO, DIR, LANGUAGE, PARTSTAT, ROLE, RSVP, SENT-BY
- Consistent with Event.new() pattern
✅ **Comprehensive test suite:**
- 25 test cases covering all parameters and edge cases
- Integration test with Event attendees
- Error condition testing
- Example usage demonstrations
✅ **Documentation:**
- Detailed docstring with parameter descriptions
- Usage examples in docstring
- RFC 5545 compliance maintained
```python
addr = vCalAddress.new("user@example.com")
addr = …
```
=> Add new() method to vCalAddress class (fixes #870)
