collective/icalendar

docs/install.rst
Just a small change to grammar to make file more readable
=> Grammar Change

src/icalendar/tests/test_timezoned.py
=> Fix tests for dateutil 2.5

docs/usage.rst
Hi there,
i fixed a few typos in the "usage" documentation.
Cheers,
tpltnt
=> Usage typo fixes

.travis.yml
=> Test with pypy and pypy3

CHANGES.rst, src/icalendar/prop.py, src/icalendar/tests/test_unit_cal.py
fixes #155
This is a simpler alternative to #222 with hopefully none of its problems.
=> Allow ignoring of TZ offsets > 24h

README.rst
=> Update README.rst - added icalevents as related project

CHANGES.rst, src/icalendar/cal.py, src/icalendar/prop.py, src/icalendar/tests/test_timezoned.py
=> Categories to be comma separated list 

README.rst
This adds the two badges for the versions we want to support
See https://github.com/collective/icalendar/discussions/360#discussioncomment-3120708
=> update badges in README

.github/workflows/tests.yml, docs/install.rst, tox.ini
This is a start to build the documentation using tox.
=> use tox to build the documentation

README.rst
This extends the list of the related projects.
=> add links to two libraries that build on top of icalendar

.github/workflows/tests.yml
This adds test runs for Python 3.11.
This provides the tests runs for #330
=> add testing for Python 3.11

README.rst
=> remove markup errors

src/icalendar/cal.py, src/icalendar/tests/test_fixed_issues.py, src/icalendar/tests/test_icalendar.py, src/icalendar/tests/test_property_params.py, src/icalendar/tests/test_unit_cal.py, src/icalendar/timezone_cache.py
=> Fixed small typos

docs/usage.rst
There more be more places in the doc, where this is required. I was not 100% sure, so I only fixed this obvious, confirmed bug.
=> Fix ical printing doc

src/icalendar/prop.py, src/icalendar/tests/test_unit_prop.py
=> add __eq__ to icalendar.prop.vDDDTypes

setup.py, src/icalendar/tests/test_fixed_issues.py, src/icalendar/tests/test_timezoned.py
this fixes https://github.com/collective/icalendar/issues/335
=> test UTC identification

.github/workflows/tests.yml
According to our compatibility goal, we can test that here, too. Let's see if it works!
=> add pypy for testing on branch 4.x

src/icalendar/tests/conftest.py
splitting into smaller PRs per #400
=> test restructure - add conftest

docs/index.rst, docs/install.rst, docs/maintenance.rst
This is a contribution towards the clarity of maintaining and releasing.
=> Document maintenance

CHANGES.rst, docs/credits.rst, src/icalendar/cli.py, src/icalendar/tests/test_cli_tool.py
Fix: https://github.com/collective/icalendar/issues/354
=> fix: cli does not support DURATION #354

CHANGES.rst, docs/changelog.rst, docs/contributing.rst, docs/credits.rst, docs/index.rst
Add Changelog and Contributing guide 
This pull request closes issue #428
=> Add Changelog and Contributing to documentation

.github/workflows/tests.yml, tox.ini
See https://github.com/collective/icalendar/issues/446
=> Run the plone.app.event tests to see if our dev version causes problems

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/empty-issue.md
This adds two issue templates to speed up reporting and ease development.
=> Add issue templates

CHANGES.rst, setup.py
I went through the pull requests and added some changelog entries.
#429
=> add changelog entries for release 5.0.0

docs/maintenance.rst
This documents the release process used for v5.0.0 #429.
=> Document release process

src/icalendar/tests/test_property_params.py
refactoring of test_property_params
=> refactor test_parameters_class

src/icalendar/tests/test_property_params.py
refactoring of test_property_params
=> refactor test_quoting

CHANGES.rst
Oi Oi, merged my own PR in #445 and here is the mistake I made!
=> move doctest change to latest version

docs/maintenance.rst
see https://github.com/collective/icalendar/discussions/360#discussioncomment-3969283
=> add jacadzaca as maintainer

CHANGES.rst, docs/install.rst, src/icalendar/__init__.py
=> version 5.0.4

src/icalendar/tests/calendars/issue_348_exception_parsing_value.ics, src/icalendar/tests/test_issue_348_exception_parsing_value.py
see https://github.com/collective/icalendar/issues/348
This reproduces the error mentioned in the issue.
To fix this, please create a PR based on this branch (to master or to this branch)
=> reproducing the error if no : is given

docs/install.rst, src/icalendar/__init__.py
Following https://github.com/collective/icalendar/pull/515#issue-1666250136
=> version 5.0.5

CHANGES.rst, docs/install.rst, src/icalendar/__init__.py
following the release process https://icalendar.readthedocs.io/en/latest/maintenance.html#new-releases
=> version 5.0.8

CHANGES.rst, docs/install.rst, src/icalendar/__init__.py
following https://icalendar.readthedocs.io/en/latest/maintenance.html#new-releases
=> version 5.0.9

CHANGES.rst, docs/install.rst, src/icalendar/__init__.py
contributes to https://github.com/collective/icalendar/issues/557
=> version 5.0.10

.github/workflows/tests.yml
=> remove spaces in front of github release section

CHANGES.rst, docs/install.rst, src/icalendar/__init__.py
following https://icalendar.readthedocs.io/en/latest/maintenance.html
=> version 5.0.11

.github/workflows/tests.yml, CHANGES.rst
This updates versions of GitHub Action steps.
=> update workflow versions

.github/dependabot.yml, news/591.minor-changes
* https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
=> Keep GitHub Actions up to date with GitHub's Dependabot

src/icalendar/tests/test_equality.py
reduce the code duplication
test more cases in the same way
This is another test refactoring.
See also #532
=> Improve equality tests

src/icalendar/tests/test_icalendar.py
This is another test refactoring.
See also #532
=> Move imports to top

CHANGES.rst, docs/install.rst, news/591.minor-changes, src/icalendar/__init__.py
see https://icalendar.readthedocs.io/en/latest/maintenance.html
=> version 5.0.12

CHANGES.rst, src/icalendar/windows_to_olson.py
Reported in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1069841
=> Use non deprecated name for America/Nuuk

CHANGES.rst, docs/credits.rst, docs/usage.rst
As described in #612 I struggled a little and read parts of the awesome library code and the RFC to understand how to do alerting and recurrence. This PR aims to extend the existing example a little for upcoming visitors.
I saw that there is a `test_examples.py` that does what parts of the examples do but it looks a little different. If you want me to adjust the test in this PR, @jacadzaca  please feel free to drop a comment.
=> Extend the existing example with alarms and recurrence-rule

CHANGES.rst, docs/install.rst
This is a nice add-on for maintainers.
=> Document how to access the documentation in the browser

CHANGES.rst, docs/install.rst, src/icalendar/__init__.py
=> version 5.0.13

CHANGES.rst, docs/about.rst, docs/usage.rst, src/icalendar/cal.py, src/icalendar/parser.py, src/icalendar/prop.py, src/icalendar/tests/prop/test_unit.py, src/icalendar/tests/test_parsing.py, src/icalendar/tests/test_unit_cal.py
=> Rename all references of RFC 2445 to RFC 5545

CHANGES.rst, README.rst
=> Move Python versions into badge

CHANGES.rst
=> Remove ... in changelog

CHANGES.rst, tox.ini
This updates the tox environment list.
See #630
=> update tox enviroment list

CHANGES.rst
#634 did not have a changelog entry.
=> log changes from PR 634

CHANGES.rst, README.rst
This removes the old version badge.
=> remove 4.x badge

CHANGES.rst, README.rst
This adds a test coverage badge from coveralls.
=> Add badge for test coverage

src/icalendar/prop.py, src/icalendar/tests/prop/test_unit.py
=> Solve issue #610

README.rst
----
📚 Documentation preview 📚: https://icalendar--714.org.readthedocs.build/
=> Improve code highlight in README.rst

CHANGES.rst, src/icalendar/__init__.py, src/icalendar/parser.py, src/icalendar/parser_tools.py
Caught by stubtest in python/typeshed#12706.
----
📚 Documentation preview 📚: https://icalendar--715.org.readthedocs.build/
=> Fix a few __all__ lists

CHANGES.rst
following https://icalendar.readthedocs.io/en/latest/maintenance.html
----
📚 Documentation preview 📚: https://icalendar--727.org.readthedocs.build/
=> version 6.0.1

README.rst
- add ics-query
- correct class reference
----
📚 Documentation preview 📚: https://icalendar--734.org.readthedocs.build/
=> [docs] Update related projects

src/icalendar/cli.py, src/icalendar/prop.py, src/icalendar/tests/test_cli_tool.py, src/icalendar/tests/test_period.py, src/icalendar/tests/test_unit_caselessdict.py, src/icalendar/tests/test_unit_parser_tools.py
#698 
----
📚 Documentation preview 📚: https://icalendar--751.org.readthedocs.build/
=> Improve coverage in 5 spots

src/icalendar/prop.py
----
📚 Documentation preview 📚: https://icalendar--752.org.readthedocs.build/
=> Add link to RFC 5545 Section 3.3.10

CHANGES.rst
following https://icalendar.readthedocs.io/en/latest/maintenance.html
----
📚 Documentation preview 📚: https://icalendar--773.org.readthedocs.build/
=> version 6.1.1

CHANGES.rst
see https://icalendar.readthedocs.io/en/latest/maintenance.html#new-releases
----
📚 Documentation preview 📚: https://icalendar--794.org.readthedocs.build/
=> version 6.1.3

CHANGES.rst, docs/about.rst, docs/conf.py, pyproject.toml, requirements_docs.txt
Fixes #804.
----
📚 Documentation preview 📚: https://icalendar--807.org.readthedocs.build/
=> Switch to PyData Sphinx Theme for documentation

CHANGES.rst
See https://icalendar.readthedocs.io/en/latest/maintenance.html
----
📚 Documentation preview 📚: https://icalendar--824.org.readthedocs.build/
=> version 6.2.0

CHANGES.rst, src/icalendar/tests/test_issue_336_dateutil_timezone.py
=> Test that issue 336 can be closed

CHANGES.rst, src/icalendar/prop.py, src/icalendar/tests/test_issue_301_add_rrule_as_string.py
This fixes #301 
----
📚 Documentation preview 📚: https://icalendar--832.org.readthedocs.build/
=> Add documentation and tests to fix issue 301

CHANGES.rst, pyproject.toml, src/icalendar/__init__.py, src/icalendar/error.py, src/icalendar/tests/test_unit_tools.py, src/icalendar/tools.py
This fixes #816
----
📚 Documentation preview 📚: https://icalendar--834.org.readthedocs.build/
=> Deprecate the UID Generator

CHANGES.rst
following https://icalendar.readthedocs.io/en/latest/maintenance.html
----
📚 Documentation preview 📚: https://icalendar--839.org.readthedocs.build/
=> version 6.3.0

CHANGES.rst
https://icalendar.readthedocs.io/en/latest/maintenance.html
----
📚 Documentation preview 📚: https://icalendar--851.org.readthedocs.build/
=> version 6.3.1
